<?php

function expert_pages_menu() {
  $items = array();
  
  $items['my-expert/todos'] = array(
    'title' => 'My Todos',
    'description' => 'My todos',
    'page callback' => 'expert_pages_my_todo',
    'access arguments' => array('access expert pages'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'pages/expert.todos.inc',
  );
  
  $items['my-expert/profile'] = array(
    'title' => 'My profile',
    'description' => 'My profile',
    'page callback' => 'expert_pages_my_profile',
    'access arguments' => array('access expert pages'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'pages/expert.profile.inc',
  );
  
  return $items;
}

function expert_pages_permission() {
  return array(
    'access expert pages' => array (
      'title' => t('Access expert pages'),
      'description' => t('Has access to the expert pages'),
    ),
  );
}

function expert_pages_theme() {
  return array(
    'expert_pages_dashboard' => array(
      'render element' => 'elements',
      'file' => 'theme/expert.dashboard.inc',
    ),
    'expert_pages_dashboard_block' => array(
      'render element' => 'elements',
      'file' => 'theme/expert.dashboard.inc',
    )
  );
}